version: '2'

services:
  www_novo_servidoradv:
    image: servidoradv/site_novo

    ports:
      - "8001:8001"

    environment:
      - DEBUG=error

  redis:
    image: redis:alpine
    volumes:
      - /var/app/site/cache:/data
