version: '2'

networks:
  balancer_site_network:
    external: true

services:
  www_novo_servidoradv:
    image: nginx:alpine
    volumes:
      - /var/app/site/novo/src:/usr/share/nginx/html:ro

    networks:
      - balancer_site_network

    ports:
      - "8001:80"
      - "8031:443"
