version: '2'

services:
  www_novo_servidoradv:
    image: servidoradv/site_novo

    ports:
      - "8001:8001"

    environment:
      - DEBUG=error,info,fine

  redis:
    image: redis:alpine
    volumes:
      - /var/app/site/cache:/data

  prerender:
    image: mondora/prerender
    ports:
      - "3333:3000"
